nfc-tools/libnfc

libnfc/buses/uart.c

Some USB-serial adapters just use tty.usbserial or tty.usbmodem as a
device name. (e.g.
Prolific).  Currently part of a patch for homebrew here:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libnfc.
rb

Use more serial devices on Mac OS X

---

libnfc/chips/pn53x.c

When there is no tag on PN532 reader, the library
incorrectly processed call result and returned
NFC_ECHIP (chip error) instead of 0 (no targets
found).

Fix nfc_initiator_poll_target without tag on PN532

---

libnfc/Makefile.am

We had an issue making https://github.com/xantares/nfc-bindings work. Fix was to expose iso_14443b* related crc symbols. Fix done by https://github.com/akito45 .

export iso14443b* symbols

---

examples/nfc-poll.c

When the polling ends without having found any target, `nfc_initiator_target_is_present` fails due to invalid argument because the code is executed in both cases (target found or not).
> No target found.
> nfc_initiator_target_is_present: Invalid argument(s)
> Waiting for card removing...done.

Fix nfc-poll card removing check

---

utils/nfc-mfclassic.c

*Current Situation*
- nfc-mfclassic knows two types of magic cards: direct-write, or 'full magic' cards. 
- 'Full magic' cards can use the R/W flags [fully unlocked read / writes]
- 'Direct Write' cards are designated by the 'magic2' flag, and must use the w/r flags.
If a 'Direct Write' card is used with a R/W flag, an error is thrown, and the program halts
*Proposed Situation*
- If a 'Direct Write' card is used with a R/W flag, a warning is shown, and the program gracefully degrades to 'standard' operation for Direct Write cards.
This seems to be a more logical behavior, allowing a user to place their 'magic' card (of any type) - using the 'R/W' flags, and getting a known result - useful in automated situations.
This code has been tested with both types of magic cards, and works …

Unlock read/write magic card fallback

---

utils/nfc-mfultralight.c

PR goal is to extend functionality for Magic UL cards.
- Added CLI flag: --check-magic - checks to see if the detected card is a mifare ultralight magic card
- Added various CLI flags to allow for unattended operation
- --otp will automatically write the OTP
- --lock will automatically write the lockbits
- --uid will automatically write the UID
- --full will write the entire card (UID, Lockbits, OTP, data..)
- Cleaned up help
- Cleaned up typos

Extends nfc-mfultralight functionality (Magic cards, unattended mode)

---

libnfc/nfc.c

A for loop condition is always false so `pnd->name` is not initialized.
This results in garbage when printing device name.

А typo leads to improper pnd->name initialization

---

HACKING.md
README-Windows.md
README.md

As promised from #341. 
Now the Readme and Hacking files are using the Markdown extension, the code parts of the files are now more humanly readable.

Actual Markdown for the README and HACKING files

---

utils/nfc-mfultralight.c

Adds support for Magic MF Ultralight Gen 2 tags.
These tags are unlocked with the 'standard' 0x40 / 0x43 commands.
Once unlocked, the badge is written as per normal.

Adding support for UL Gen 2 Badges

---

configure.ac

NEWS and README are mandatory for autoconf. Fixes problem introduced in
b1a81b385ddabb704b4cea64fda56abb9928c3c3
closes https://github.com/nfc-tools/libnfc/pull/346
fixes https://github.com/nfc-tools/libnfc/issues/347

tell Automake that we will not follow GNU Standards

---

utils/nfc-mfclassic.1
utils/nfc-mfclassic.c
utils/nfc-mfultralight.c

This patch series does some code cleanup/fixups on a small scale, but most importantly adds the ability to specify UID's to mfc-classic and mfultralight tools to r/w a specific tag when multiple tags are insight.

Allow mfultralight and mfc tools to work also with specific UID's

---

libnfc/drivers/acr122_usb.c

added ACR1222U-C1 ACS ACR1222 1SAM PICC Reader in supported devices

added support for ACR1222U-C1

---

libnfc/chips/pn53x-internal.h
libnfc/drivers/pn532_i2c.c

The pn532 states in its datasheet that the i2c stop and start conditions require atleast 1.3 ms between them. Currently, there is a nanosleep of 90 ms which seems arbitrarily chosen (nothing in the comments/git log from it). A delay however is always needed, as otherwise we write to fast for sure.
Additionally, this delay is not always added everywhere, so we still sometimes send data way to fast for the pn532. This patch creates wrappers around i2c_read and i2c_write to ensure proper timing of read and write commands.
Additionally we clarify the preamble/start condition a bit, as there was a bug in the text. No code changes where done in that regard.
Note, I have tested it on one board on one machine and not yet endlessly. So I'd like to first properly review this first before merging :) …

Respect pn532 i2c timing

---

libnfc/drivers/pn532_i2c.c

The datasheet is wrong for the pn532_i2c. After having constant issues
with the device failing to respond on the bus and after contacting NXP
about this, it turns out 1.3 ms is too tight. The official timing spec
is unknown for now, but we tested 4 and 5 ms without problems. Thus we
have choosen 5 ms as a safe delay.
Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>

drivers: pn532_i2c: Errata on i2c timing

---

examples/nfc-mfsetuid.c
utils/nfc-mfclassic.c

Integrates a new type of Chinese Magic 4K card, 'generation b'. This chipset was [recently integrated](http://www.proxmark.org/forum/viewtopic.php?id=4512) into the proxmark codebase, so it seems to make sense to provide compatibility here. 
The chipset in question only needs the command 0x40 to be unlocked, but does not provide an ACK to this command. As such, nfc-mfclassic now will allow for 'failed' unlock commands, but will provide sensible failure messages for cards that cannot be unlocked, ie:
```
./nfc-mfclassic R a u /tmp/4k.dmp
NFC reader: PN532 board via UART opened
Found MIFARE Classic card:
ISO/IEC 14443A (106 kbps) target:
ATQA (SENS_RES): 00  04
UID (NFCID1): 9c  21  45  75
SAK (SEL_RES): 08
Guessing size: seems to be a 1024-byte card
Sent bits:     50  00  57  cd
Sent bits: …
```

Adding support for 4K magic cards

---

examples/nfc-emulate-tag.c

Wrong variable names (missing dots) on line 269, 270, 271

Wrong variable names

---

utils/nfc-mfclassic.c

This PR removes redundant blanks from `nfc-mfclassic.c`.

Remove redundant blanks from nfc-mfclassic.c

---

utils/nfc-mfclassic.c

This PR fixes a typo in `nfc-mfclassic` output.

Fix typo in nfc-mfclassic

---

utils/nfc-relay-picc.1
utils/nfc-relay-picc.c

A few hours ago I had the problem that I wanted to use nfc-relay-picc but my 2 NFC devices got assigned their roles in the wrong order. When I tried to do a quick'n'dirty patch to swap this, I realyzed that this functionality already exists and there's even already an command line option for that: **-s**
Unfortunately this isn't listed in either the usage screen nor the man page, which is fixed by this pull request.

Add undocumented option -s to nfc-relay-picc help

---

libnfc/chips/pn53x.c

Add a timeout in pn53x_initiator_select_passive_target()
so that we do not get stuck forever when pn533 misses a toggle
bit change.

Add missing timeout

---

libnfc/drivers/pn53x_usb.c

PN533 easily corrupts its USB descriptors. We know that and we
already try to detect and even repair them.
However there are situations where lower software layers get
confused before libnfc can help. On Windows, libusb may set
dev->config to NULL, but we can also have a non NULL dev->config
referencing corrupted data.
In order to get more robust, let us replace the Windows libusb
specific (dev->config == NULL) test by an inconditionnal use of
hardcoded descriptors when they are available.

Prefer hardcoded PN533 descriptors to the real ones

---

examples/nfc-emulate-uid.1

Nothing major, changed the word "thread" with the word "threat", which is the right word to use in the given context.

Fixed a typo in examples/nfc-emulate-uid.1

---

.travis.yml
utils/nfc-mfclassic.c
utils/nfc-mfultralight.c

Commit adds support for multiple types of newer magic cards:
- Ultralight "DirectWrite" tags
- Mifare 1k/4k "DirectWrite" tags
- Mifare 1k "One Time Write" tags
"DirectWrite" tags allow modification of B0 without any unlock codes. They are used frequently on Android systems, where custom unlock commands cannot be sent due to firmware restrictions.
Further, unlock codes are known to brick several types of Ultralight DirectWrite tags. As such, we attempt to manipulate B0 directly as an initial check, before issuing unlock commands.
"One Time Write" tags allow the UID to be modified exactly one time. They are delivered from the factory with a fixed UID, which we use to determine if the card is One Time Write / magic.
Thanks to @daniellebruneo for his extensive work in debugging and testing …

Adding extended Magic Card support

---

utils/nfc-mfclassic.c

This PR adds output to nfc-mfclassic indicating whether the card supports RATS or not.

Add RATS support indicator to nfc-mfclassic

---

libnfc/buses/usbbus.h

stdint.h is needed for uintX_t typedefs which are
used to replace u_intX_t in libusb API headers in the cmake files
Define _GNU_SOURCE since thats not defined by default for musl
C library on linux
Signed-off-by: Khem Raj <raj.khem@gmail.com>

usbbus: Include stdint.h for uintX_t

---

libnfc/drivers/acr122_usb.c

Quick and dirty fix #535 
I'm not sure but I think, that the 072f:2200-device does not support alernative usb modes:
```shell
Bus 001 Device 013: ID 072f:2200 Advanced Card Systems, Ltd ACR122U:
bAlternateSetting       0
```
Disabling allows to read and write:
```
./nfc-mfclassic r u a test.mfd
./nfc-mfclassic w u a test.mfd
```
I'm not sure. But does any of these acr122-devices has an alternative usb mode?

Added check for USB alternate settings

---

README.md
libnfc/drivers/pcsc.c

1. Modify pcsc.c code, add R502 and bR500 support into PCSC driver
2. Update readme, tell user how to build with pcsc driver
3. Add FAQ for bR500 and R502 in readme

Update readme and add Feitian R502 and bR500 support into pcsc driver

---

configure.ac
libnfc/drivers/Makefile.am
m4/libnfc_drivers.m4

If the user specifically requests the driver, throw an error if it cannot find libnfc-nci.
Also use the value from pkg-config to determine the library name, instead of hard-coding it.

Add check for Libnfc-NCI before enabling pn71xx

---

libnfc/drivers/pcsc.c
utils/mifare.c

Modify pcsc.c and mifare.c files.
1. add code into pcsc.c to have support Mifare classic card.
2. The PCSC reader has SW value, add response data length for PCSC
reader

Modify pcsc.c to have support for Mifare classic and Ultralight card

---

libnfc/drivers/pcsc.c

improve the code, to have compatible with OEM R502.
In the PC/SC reader, the response code has two bytes, SW1 and SW2, but some Feitian reader with OEM firmware, which only return 1 byte, which lead the problem at high level API call. add length check and avoid this problem.

Add length check when work with Feitian OEM R502

---

Makefile.am
configure.ac

This patch makes example build optional for autotools build system.
In order to keep the former behavior, example build is enabled by default.
Signed-off-by: Samuel Martin <s.martin49@gmail.com>
[Retrieved (and slightly updated to remove CMakeLists.txt) from:
https://git.buildroot.net/buildroot/tree/package/libnfc/0001-build-systems-make-example-build-optional.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

autotools: make example build optional

---

utils/nfc-mfclassic.c

Ok, my ocd wins..
There is a rework including @AdamLaurie commits.
Tested before and after on genuine and gen2. 
Now you can rewrite gen2 with W, please see commit descs

Improve support for gen2 and gen3 tags

---

utils/nfc-list.c

nfc-list always prints the version number.  
```
user@happycow:~/abc$ nfc-list
nfc-list uses libnfc libnfc-1.8.0-6-g4b7791f
```
This PR aims to make that printing follow the verbose flag instead for a cleaning output.

chg: make version printing obey verbose flag

---

contrib/win32/libnfc/buses/uart.c
libnfc/drivers/acr122_usb.c
libnfc/drivers/acr122s.c
libnfc/drivers/arygon.c
libnfc/drivers/pn532_uart.c
libnfc/drivers/pn53x_usb.c

There is a small typo in contrib/win32/libnfc/buses/uart.c, libnfc/drivers/acr122_usb.c, libnfc/drivers/acr122s.c, libnfc/drivers/arygon.c, libnfc/drivers/pn532_uart.c, libnfc/drivers/pn53x_usb.c.
Should read `mechanism` rather than `mecanism`.

docs: fix simple typo, mecanism -> mechanism

---

libnfc/drivers/pcsc.c

Follow the NXP  Contactless card IC rules to be compatible with Feitian new and old R502 reader.

Modify code to add compatibility of readers

---

libnfc/drivers/pcsc.c

atqa became ataq, causing build to naturally fail.

Fix typo in variable name in pcsc.c

---

README.md

Addresses #593.
Build and install instructions are now helpful to people who download via git.
I have assumed that `make install` is the correct target for install, but someone should check that before merging.

Make README.md more helpful for newcommer, remove ref to missing INSTALL

---

examples/CMakeLists.txt
examples/Makefile.am
examples/nfc-st25tb.c

This new example allows to operate on some ISO-14443-B ST25TB* and legacy SR* cards (read, write, info)
It was tested with PN533 USB and:
- `ST25TB512-AC` - (BE/Brussels/STIB ; AliExpress ones)
- `ST25TB512-AT` - (FR/Lille/Ilevia ; FR/Reims/Citura)
- `SRT512` - legacy - (FR/Bordeaux/TBM)
- `SRI512` - legacy - (anonymous vending machine)
Sample outputs:
```
gentilkiwi@debian-01:~/Programmation/libnfc$ examples/nfc-st25tb
|mode   : info
Reader  : NXP / PN533 - via pn53x_usb:002:005
...wait for card...
Target  : ISO/IEC 14443-2B ST SRx (106 kbps)
UID     : b6 c0 61 a0 00 1b 02 d0
Manuf   : 0x02 - STMicroelectronics
ChipId  : 0x1b - ST25TB512-AC
Serial  : 0x00a061c0b6
|blk sz : 32 bits
|nb blks: 16
|sys idx: 255
[0x00] 7a 7f 8e 8d
[0x01] ad 40 e0 93
[0x02] bc 1e aa e0
[0x03] 09 9d 24 58 …
```

Add nfc-st25b example

---

libnfc/drivers/pcsc.c

Compiling on MacOS catalina (./configure --with-drivers=pcsc) causes the error
pcsc.c:829:9: error: implicit declaration of function 'usleep' is invalid
in C99 [-Werror,-Wimplicit-function-declaration]
usleep(500000);//delay 500ms
Including unistd.h fixes this :-)

Include unistd.h (required because of usleep())

---

libnfc/drivers/pcsc.c

In `libnfc/drivers/pcsc.c`, there is an assignment operation instead of a comparison (`=` instead of `==`). This PR replaces the operator with the correct one.

Fix - assignment instead of comparison (PCSC driver)

---

examples/nfc-st25tb.c
libnfc/chips/pn53x.c
utils/nfc-list.c

Modification to set PN53X_REG_CIU_TxAuto, PN53X_REG_CIU_CWGsP & PN53X_REG_CIU_ModGsP registers values before init. Avoids a dummy scan in B mode before

pn53x initiator set registers for ISO14443B-2 ST SRx

---

libnfc/drivers/acr122_usb.c

This patch fixes the error message and nfc-poll crash reported in #284 and #570.
Though I am not the author, any chance you could merge this?

Fixes error libnfc.driver.acr122_usb Invalid RDR_to_PC_DataBlock frame

---

README.md

Adds a section on environment variables in README.md.
Source: libnfc/nfc-internal.c

Document environment variables in README.md

---

libnfc/nfc-internal.h
libnfc/nfc.c

This pull request is intended to fix [the memory leak in nfc_initiator_select_passive_target()](https://github.com/nfc-tools/libnfc/pull/621#issue-709562960) and [refactor the HAL macro](https://github.com/nfc-tools/libnfc/pull/621#issuecomment-710029332) (to avoid returning from a macro) by using [gcc statement expressions](https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html) and close [my issue](https://github.com/nfc-tools/libnfc/issues/671).

Refactor HAL macro and fix memory leak in nfc_initiator_select_passive_target()

---

examples/nfc-st25tb.c
libnfc/chips/pn53x.c

When using `pn53x` chip with target not compatible with `InListPassiveTarget` (like `NMT_ISO14443BICLASS`, `NMT_ISO14443B2CT` & `NMT_ISO14443B2SR` by eg.), the logic behind `nfc_initiator_select_passive_target` to return target count seems to be buggy
`nfc_initiator_select_passive_target`:
> Returns:
> Returns selected passive target count on success, otherwise returns libnfc's error code (negative value)
In `pn53x_initiator_select_passive_target_ext`, the return value in success is always `abtTargetsData[0]`. This is correct when using `InListPassiveTarget` as the first byte is `NbTg`, but it can be problematic for other cases.
- Example with a Mifare:
```
gentilkiwi@pi5:~/libnfc-dev $ ./utils/nfc-list -t 1
NFC device: Elechouse NFC Module V3 (SPI) opened
1 ISO14443A passive target(s) …
```

Fix `nfc_initiator_select_passive_target` target count on PN53x when not using `InListPassiveTarget`
